spring.application.name=auth-service

# Configuración de conexión a PostgreSQL
# Cambia 'postgres' al final de la URL por el nombre de tu base de datos si es diferente
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración básica de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Variable para tu Hello World
app.greeting=Hello World! La base de datos esta conectada.
